draw_set_halign(fa_left)
if debugmode=1 {
draw_set_font(fSmall)
draw_text(15,20*1,"-----MOVEMENT-----")
draw_text(15,20*2,string(hspd)+" hspd")
draw_text(15,20*3,string(vspd)+" vspd")
draw_text(15,20*4,string(spd)+" spd")
draw_text(15,20*5,string(maxspd)+" maxspd")
draw_text(15,20*6,string(global.mrot)+" meteor rotation")
draw_text(15,20*7,string(global.mspd)+" meteor speed")
						 
draw_text(15,20*9,"-----COUNTING AND COOLDOWNS-----")
draw_text(15,20*10,string(global.count)+" amount of meteors killed by bullet")
draw_text(15,20*11,string(global.mactives)+" amount of meteors alive (actual limit = "+string(global.mlimit)+")")
draw_text(15,20*12,string(global.lives)+" lifes")
draw_text(15,20*13,string(shotcol)+" shot cooldown")
draw_text(15,20*14,string(hitcooldown)+" hit cooldown")
						 
draw_text(15,20*16,"-----PAUSE AND CONFIGS-----")
draw_text(15,20*17,string(global.pause)+" pause")
draw_text(15,20*18,string(global.musicvolume)+" music volume")
draw_text(15,20*19,string(global.soundsvolume)+" sounds volume")
						 
draw_text(15,20*21,"-----HABILITIES STUFF-----")
draw_text(15,20*22,string(global.hab3)+" hab 3")
draw_text(15,20*23,string(global.hab3disp)+" hab 3 display")
draw_text(15,20*24,string(habrandom)+" hab random")
draw_text(15,20*25,string(global.bombs)+" bombs")
draw_text(15,20*26,string(global.bdamage)+" bomb damage")
draw_text(15,20*27,string(global.destroyshield)+" global destroy shield")
draw_text(15,20*28,string(global.deaths)+" deaths")
						 
draw_text(15,20*30,string(repeated)+" repeated")
draw_text(15,20*31,string(damaged)+" damaged")
draw_text(15,20*32,string(damageSkin)+" damageSkin")
draw_text(15,20*33,string(DamageBoolean)+" damageBoolean")
draw_text(15,20*34,string(global.skin)+" skin")
draw_text(15,20*35,string(global.breload)+" bomb reload")
}
draw_sprite_ext(global.skin,0,x,y,1,1,image_angle,c_white,image_alpha)
